# Generated by Django 5.1.2 on 2024-10-21 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='explanation',
            field=models.CharField(default='No information has been entered (yet).', max_length=500),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='explanation',
            field=models.CharField(default='No information has been entered (yet).', max_length=500),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
