# Generated by Django 5.1.2 on 2024-10-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercategory_usersubcategory_userprompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userprompts',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
